; N'affiche jamais les erreurs/warnings/deprecated dans le navigateur
display_errors = Off
display_startup_errors = Off
 
; Log toutes les erreurs (y compris deprecated et warnings) dans un fichier
log_errors = On
error_reporting = E_ALL
error_log = /var/log/apache2/php_errors.log
 